baseURL = 'https://lorenjohnson.netlify.app/'
languageCode = 'en-us'
title = 'Loren Johnson is going to stay human'
theme = ["hugo-theme-console", "hugo-video"]

[security]
  enableInlineShortcodes = true
