baseURL = 'https://lorenjohnson.netlify.app/'
languageCode = 'en-us'
title = 'Loren Johnson '
theme = ["hugo-theme-console", "hugo-video", "hugo-shortcode-gallery"]
timeout = 120000

[security]
  enableInlineShortcodes = true
